version: "3.7"
services:

  app:
    build:
      context: .
    environment:
      MYAPP_DSN: "dbname=docker user=docker password=password host=postgres sslmode=disable"

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-postgres}"
      POSTGRES_DB: "${POSTGRES_DB:-postgres}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-mysecretpassword}"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
